version: "2"


services:
  postgres:
    image: bitnami/postgresql:15
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - "5435:5432"

  service:
    &service
    build: .
    image: xart/service:latest
    depends_on:
      postgres:
        condition: service_started
    environment:
      - pg_host=postgres
      - ph_port=5432

  migration:
    <<: *service
    command: make migrate

  backend:
    <<: *service
    ports:
      - "9000:9000"
    command: python manage.py runserver

  init_users:
    <<: *service
    command: python manage.py init_users

  populate_data:
    <<: *service
    command: python manage.py populate_data
