"""update table

Revision ID: 28f86aa65af4
Revises: 7cc9cff0df01
Create Date: 2023-03-05 23:42:33.557954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f86aa65af4'
down_revision = '7cc9cff0df01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('file_name', sa.String(), nullable=False))
    op.create_unique_constraint("product_file_name_key", 'product', ['file_name'])
    op.drop_column('product', 'image_path')
    op.add_column('snapshot', sa.Column('file_name', sa.String(), nullable=False))
    op.create_unique_constraint("snapshot_file_name_key", 'snapshot', ['file_name'])
    op.drop_column('snapshot', 'image_path')
    op.alter_column('voting', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('voting', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('voting', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('voting', 'challenge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voting', 'challenge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('voting', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('voting', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('voting', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('snapshot', sa.Column('image_path', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint("snapshot_file_name_key", 'snapshot', type_='unique')
    op.drop_column('snapshot', 'file_name')
    op.add_column('product', sa.Column('image_path', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint("product_file_name_key", 'product', type_='unique')
    op.drop_column('product', 'file_name')
    # ### end Alembic commands ###
